### ISSUE TITLE
Division by zero when `num` is 1 

### ISSUE THREAD

**Issue by PaulRBerg** [mds1/solidity-generators#4]
The `linspace` function does not handle the case when `num` is 1, which leads to division by zero on this line:

https://github.com/mds1/solidity-generators/blob/60e485e0076ccf62d69ef79e1e2aeaba1fee3ef5/src/Generators.sol#L48

The function should either revert or return `start`.

**Comment by mds1** [comment]
Hmm where is it not handled? From the ternary, when `num == 1` we set the step size to zero and don't divide by `num - 1`

**Comment by PaulRBerg** [comment]
Brain fog two days ago. Sorry!
